### ISSUE TITLE
API Key on public repo

### ISSUE THREAD

**Issue by OusmaneKana** [CY83R-3X71NC710N/Weather-Dashboard-Updater#637]
I just noticed that you had your Weather API key public. Maybe put it as environment variable or .dotenv would be safer ?

**Comment by CY83R-3X71NC710N** [comment]
I see thank you for the idea

**Comment by CY83R-3X71NC710N** [comment]
I will do this

**Comment by CY83R-3X71NC710N** [comment]
Mainly I left it like this because it was a demo API key. But perhaps I should use enviroment variables

**Comment by CY83R-3X71NC710N** [comment]
Ultimately it would be redundant to add this to a .dotenv now as it is in the commit history so I will regenerate a new one and add it to the file.
